version: "3.9"
name: "q4-video"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_q4
    networks:
      - app-net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka_q4
    networks:
      - app-net
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: kafka-topics --bootstrap-server ${KAFKA_BOOTSTRAP_SERVERS} --list || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  redis:
    image: redis:7
    container_name: redis_q4
    ports:
      - "6379:6379"
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_q4
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres_q4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui_q4
    ports:
      - "9909:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - app-net
    depends_on:
      - kafka

  moderation_worker:
    build:
      context: ./moderation_worker
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    restart: unless-stopped
    depends_on:
      - kafka
      - rabbitmq
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    networks:
      - app-net

  vod_transcoding_worker:
    build:
      context: ./vod_transcoding_worker
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    restart: unless-stopped
    depends_on:
      - kafka
      - rabbitmq
    networks:
      - app-net
    environment:
      # Kafka
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}

      # Topics
      TRANSCODING_UPDATE_TOPIC: ${TRANSCODING_UPDATE_TOPIC}
      TRANSCODING_FINISH_TOPIC: ${TRANSCODING_FINISH_TOPIC}
      TRANSCODING_FAIL_TOPIC: ${TRANSCODING_FAIL_TOPIC}

      # AWS
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_RAW_BUCKET: ${AWS_RAW_BUCKET}
      AWS_TRANSCODED_BUCKET: ${AWS_TRANSCODED_BUCKET}

      # CDN
      CDN_BASE_URL: ${CDN_BASE_URL}

      # Key service
      PUBLIC_KEY_SERVER_URL: ${PUBLIC_KEY_SERVER_URL}

      # RabbitMQ
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_QUEUE: transcoding_jobs
      # Worker tuning
      MAX_CONCURRENT_JOBS: ${MAX_CONCURRENT_JOBS}

networks:
  app-net:
    driver: bridge

volumes:
  pg_data: {}