version: '3.8'
name: 'q4-video'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_q4
    networks:
      - app-net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka_q4
    networks:
      - app-net
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:9092 --list || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  redis:
    image: redis:7
    container_name: redis_q4
    ports:
      - "6379:6379"
    networks:
      - app-net
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_q4
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app-net
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres_q4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build:
      context: ./ServiceDiscovery
    ports:
      - "8761:8761"
    networks:
      - app-net
    depends_on:
      postgres:
        condition: service_healthy

  api-gateway:
    build:
      context: ./api_gateway
    ports:
      - "8001:8001"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
    networks:
      - app-net

  asset-onboarding:
    build:
      context: .
      dockerfile: asset_onboarding/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      EUREKA_URL: ${EUREKA_URL}
      DB_URL: ${ASSET_DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_URL: ${KAFKA_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_SECURE_BUCKET: ${AWS_SECURE_BUCKET}
      CLOUDFRONT_KEY_PAIR_ID: ${CLOUDFRONT_KEY_PAIR_ID}
      PRIVATE_KEY_PATH: ${PRIVATE_KEY_PATH}
      CDN_RESOURCE_URL: ${CDN_RESOURCE_URL}
      CDN_DOMAIN: ${CDN_DOMAIN}
    volumes:
      - ./keys:/app/keys
    networks:
      - app-net

  transcoder:
    build:
      context: ./transcoder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
      KAFKA_URL: ${KAFKA_URL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_RAW_BUCKET_NAME: ${AWS_RAW_BUCKET_NAME}
      AWS_TRANSCODED_BUCKET_NAME: ${AWS_TRANSCODED_BUCKET_NAME}
      DOCKER_TRANSCODER_CONTAINER_IMAGE: ${DOCKER_TRANSCODER_CONTAINER_IMAGE}
      CLOUD_FRONT_URL: ${CLOUD_FRONT_URL}
    networks:
      - app-net

  user:
    build:
      context: ./user
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      eureka-server:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
      DB_URL: ${USER_DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_URL: ${KAFKA_URL}
    networks:
      - app-net

  rtmp_sever:
    build:
      context: .
    depends_on:
       kafka:
        condition: service_healthy
       eureka-server:
        condition: service_healthy
    ports:
      - "8000:8000"
      - "1935:1935"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_RAW_BUCKET_NAME: ${AWS_RAW_BUCKET_NAME}
      AWS_TRANSCODED_BUCKET_NAME: ${AWS_TRANSCODED_BUCKET_NAME}
      DOCKER_TRANSCODER_CONTAINER_IMAGE: ${DOCKER_TRANSCODER_CONTAINER_IMAGE}
      CLOUD_FRONT_URL: ${CLOUD_FRONT_URL}


networks:
  app-net:
    driver: bridge

volumes:
  pg_data: {}