spring.application.name=asset-onboarding

server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vsnt_assets}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
spring.datasource.password=password



#eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.enabled=true
eureka.client.fetch-registry=true
eureka.instance.instance-id=localhost:asset-onboarding:8081
eureka.instance.prefer-ip-address=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=guest

#rabbitmq
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:15672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
