package com.vsnt.common_lib.dtos.events.asset;

public enum AssetEventType {
    ASSET_PROCESSING_STARTED,
    ASSET_PROCESSING_COMPLETED,
    ASSET_TRANSCODING_STARTED,
    ASSET_TRANSCODING_COMPLETED,
    ASSET_TRANSCODING_FAILED,
    ASSET_TRANSCODING_PROGRESS,
    ASSET_UPLOADING,
    ASSET_UPLOADED
}
