eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}"
    register-with-eureka: true


spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
       cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          allowedHeaders: "*"
          allowCredentials: true
      routes:
        - id: user
          uri: lb://user
          filters:
            - AuthenticationFilter
            - RewritePath=/api/user/(?<segment>.*), /$\{segment}
          predicates:
            - Path=/api/user/**

        - id: asset_onboarding
          uri: http://localhost:8081
          filters:
            - AuthenticationFilter
            - RewritePath=/api/asset_onboarding/(?<segment>.*),/$\{segment}
          predicates:
            - Path=/api/asset_onboarding/**

        - id: transcoder
          uri: lb://transcoder
          filters:
            - RewritePath=/api/transcoder/(?<segment>.*),/$\{segment}
          predicates:
            - Path=/api/transcoder

server:
  port: 8001

